# Generated by Django 5.2.4 on 2025-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_promotion_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='condition_min_order',
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_type',
            field=models.CharField(choices=[('product', 'Theo sản phẩm'), ('category', 'Theo danh mục'), ('order', 'Toàn đơn hàng')], default='order', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, to='app.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('money', 'Giảm theo số tiền'), ('percent', 'Giảm theo phần trăm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
