# Generated by Django 5.2.4 on 2025-10-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_promotion_condition_min_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(auto_created=True, max_length=100),
        ),
    ]
